[font]
size = 11.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[window]
decorations = "Full"
startup_mode = "Maximized"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[colors.cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.vi_mode_cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.selection]
text = "CellForeground"
background = "#4c566a"

[colors.search.matches]
foreground = "CellBackground"
background = "#88c0d0"

[colors.footer_bar]
background = "#434c5e"
foreground = "#d8dee9"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.dim]
black = "#373e4d"
red = "#94545d"
green = "#809575"
yellow = "#b29e75"
blue = "#68809a"
magenta = "#8c738c"
cyan = "#6d96a5"
white = "#aeb3bb"


[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"
